[build]
  base = "/"
  command = "env SITEURL=$DEPLOY_PRIME_URL make html"
  publish = "output"

[context.production]
  command = "env SITEURL=$URL make html"

[[redirects]]
  from = "/register"
  to = "https://sciwork.kktix.cc/events/sciwork-conference-20241214-ntu"
  force = true
